package main

// autogenerated with `python generate_ast.py .`

type Expr interface {
	accept(v ExprVisitor) interface{}
}

type Binary struct {
	left     Expr
	operator *Token
	right    Expr
}

func NewBinary(left Expr, operator *Token, right Expr) *Binary {
	return &Binary{
		left:     left,
		operator: operator,
		right:    right,
	}
}

func (b *Binary) accept(ev ExprVisitor) interface{} {
	return ev.visitBinaryExpr(b)
}

type Grouping struct {
	expression Expr
}

func NewGrouping(expression Expr) *Grouping {
	return &Grouping{
		expression: expression,
	}
}

func (g *Grouping) accept(ev ExprVisitor) interface{} {
	return ev.visitGroupingExpr(g)
}

type Literal struct {
	value interface{}
}

func NewLiteral(value interface{}) *Literal {
	return &Literal{
		value: value,
	}
}

func (l *Literal) accept(ev ExprVisitor) interface{} {
	return ev.visitLiteralExpr(l)
}

type Unary struct {
	operator *Token
	right    Expr
}

func NewUnary(operator *Token, right Expr) *Unary {
	return &Unary{
		operator: operator,
		right:    right,
	}
}

func (u *Unary) accept(ev ExprVisitor) interface{} {
	return ev.visitUnaryExpr(u)
}

type ExprVisitor interface {
	visitBinaryExpr(b *Binary) interface{}
	visitGroupingExpr(g *Grouping) interface{}
	visitLiteralExpr(l *Literal) interface{}
	visitUnaryExpr(u *Unary) interface{}
}
